# Generated by Django 6.0.3 on 2026-05-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips_app.guide')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips_app.trip')),
            ],
        ),
    ]
