# Generated by Django 6.0.3 on 2026-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0002_tripguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
