# Generated by Django 6.0.3 on 2026-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0003_alter_trip_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
