# Generated by Django 6.0.3 on 2026-05-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_event_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='margin',
        ),
    ]
