# Generated by Django 6.0.3 on 2026-05-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_event_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
