# Generated by Django 6.0.3 on 2026-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='characteristics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
